name: Local Fuzzing Test
on:
  pull_request:
    paths:
      - 'Week2/project/**'
permissions: read-all
jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
        - address
        - undefined
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y clang cmake make
        
    - name: Build fuzzers with ${{ matrix.sanitizer }}
      run: |
        cd Week2/project
        export SANITIZER=${{ matrix.sanitizer }}
        make fuzz-build
        
    - name: Verify fuzzers were built
      run: |
        cd Week2/project
        ls -la fuzz_deserialize fuzz_roundtrip
        file fuzz_deserialize fuzz_roundtrip
        
    - name: Quick smoke test
      run: |
        cd Week2/project
        timeout 5 ./fuzz_deserialize || echo "Fuzzer smoke test completed"
